FROM amazoncorretto:17
LABEL authors="Никита"
MAINTAINER roclh
COPY telegram-discord-bot-0.0.1-SNAPSHOT.jar /home/telegram-discord-bot.jar
ENTRYPOINT ["java", "-jar", "/home/telegram-discord-bot.jar"]